#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: pihole-pv
#spec:
#  capacity:
#    storage: 1Gi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: rook-ceph-block-retain
#  csi:
#    driver: rook-ceph.rbd.csi.ceph.com
#    fsType: ext4
#    volumeHandle: pihole-pv
#---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc2
  namespace: pihole-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: iscsi
  #volumeName: pihole-pv